version: '2.4'

services:

  # postgres_db:
  #   extends:
  #     file: ../Lezzetly/docker-compose.yml
  #     service: postgres
  #   container_name: postgres_db

  postgres:
    image: postgres:9.6.6
    restart: always
    volumes:
        - ./pgdb/:/var/lib/postgresql/
    ports:
        - "5432:5432"
    env_file: ./.env
  
  app:
    container_name: client_app
    image: client_app
    build: .
    ports:
      - 8004:8000
    restart: on-failure
    volumes:
        - .:/code/
    depends_on:
        - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080